table 'ARR Bridge'

	column month_start
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: month_start

	column opening_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: opening_arr_usd

	column new_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: new_arr_usd

	column expansion_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: expansion_arr_usd

	column contraction_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: contraction_arr_usd

	column churn_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: churn_arr_usd

	column ending_arr_usd
		dataType: double
		formatString: $#,0;($#,0);-
		summarizeBy: none
		sourceColumn: ending_arr_usd

	column active_customers
		dataType: int64
		summarizeBy: none
		sourceColumn: active_customers

	partition 'ARR Bridge' = m
		mode: import
		source =
			let
				Source = Csv.Document(
					Web.Contents(RepositoryRawBaseUrl & "data/processed/04_arr_bridge.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				Typed = Table.TransformColumnTypes(
					Headers,
					{{"month_start", type date},
					{"opening_arr_usd", type number},
					{"new_arr_usd", type number},
					{"expansion_arr_usd", type number},
					{"contraction_arr_usd", type number},
					{"churn_arr_usd", type number},
					{"ending_arr_usd", type number},
					{"active_customers", Int64.Type}},
					"en-US"
				)
			in
				Typed
