table DimDate
	dataCategory: Time

	column month_start
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: month_start

	column calendar_year
		dataType: int64
		summarizeBy: none
		sourceColumn: calendar_year

	column calendar_quarter
		dataType: string
		summarizeBy: none
		sourceColumn: calendar_quarter

	column month_number
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number

	column month_name
		dataType: string
		sortByColumn: month_number
		summarizeBy: none
		sourceColumn: month_name

	column fiscal_year
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_year

	column fiscal_quarter
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_quarter

	column period_status
		dataType: string
		summarizeBy: none
		sourceColumn: period_status

	partition DimDate = m
		mode: import
		source =
			let
				Source = Csv.Document(
					Web.Contents(RepositoryRawBaseUrl & "data/raw/dim_date_month.csv"),
					[Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				Typed = Table.TransformColumnTypes(
					Headers,
					{{"month_start", type date},
					{"calendar_year", Int64.Type},
					{"calendar_quarter", type text},
					{"month_number", Int64.Type},
					{"month_name", type text},
					{"fiscal_year", type text},
					{"fiscal_quarter", type text},
					{"period_status", type text}},
					"en-US"
				)
			in
				Typed
